services:
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    networks:
      - internal

  basicstation:
    image: xoseperez/basicstation:latest
    container_name: basicstation
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      MODEL: ${MODEL}
      TC_KEY: ${TC_KEY}
      INTERFACE: ${INTERFACE}
      RESET_GPIO: ${RESET_GPIO}
      DEVICE: ${DEVICE}
      HAS_GPS: ${HAS_GPS}
      
    
  gateway-mqtt-publisher:
    build:
      context: ./log-publisher
      dockerfile: Dockerfile
    container_name: gateway-mqtt-publisher
    restart: unless-stopped
    depends_on:
      - basicstation
    environment:
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}
      MQTT_TOPIC_PREFIX: ${MQTT_TOPIC_PREFIX}
      BASICSTATION_CONTAINER: ${BASICSTATION_CONTAINER}
      TTN_CLUSTER: ${TTN_CLUSTER}
      TTN_GATEWAY_ID: ${TTN_GATEWAY_ID}
      DEBUG: ${DEBUG}
      TTN_API_KEY: ${TTN_API_KEY}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
   
networks:
  internal:
    driver: bridge
    